// react/src/components/FormilyPage/index.tsx
import React, { useState, } from 'react'

import { createForm, Form } from '@formily/core'
import { FormProvider, FormConsumer, createSchemaField, JSXComponent } from '@formily/react'

import * as FormilyAntd from '@formily/antd'
import * as ProjectComponents from './projectComponents'
import {  } from './transformComponent'
import * as AdminTemplateScope from './adminTemplateScope'

import { ISchema } from '@formily/json-schema'
import { NavLink } from 'react-router-dom'

export interface DesignablePage {
    form: {
        labelCol: Number,
        wrapperCol: Number
    },
    schema: ISchema
}

interface FormilyPageProps {
  schema: DesignablePage,
  schemaKey?: string,
  components?: {
    [key: string]: JSXComponent
  },
  scope?: Object,
  effects?: (form: Form) => void
}

const SchemaField = createSchemaField({
  components: {
    ...FormilyAntd,
    // Input: Object.assign(
    //   transformNativeOn(FormilyAntd.Input),
    //   {
    //     TextArea: transformNativeOn(FormilyAntd.Input.TextArea)
    //   }
    // ),
    // Password: transformNativeOn(FormilyAntd.Password),
    // Radio: FormilyAntd.Radio,
    ...ProjectComponents
  }
})

export const FormilyPage: React.FunctionComponent<FormilyPageProps> = ({ schema, schemaKey, components, effects, scope }) => {
  const form = createForm({
    effects
  })
  const scopeWithAT = {
    ...AdminTemplateScope,
    ...scope,
  }
  return (
    <FormProvider form={form}>
      <slot name="before" />
      <SchemaField schema={schema.schema} components={components} scope={scopeWithAT} />
      <slot name="default" />
      <FormConsumer>
        {form => (
          schemaKey ? <NavLink to={'/designable?key=' + schemaKey}>编辑</NavLink> : null
        )}
      </FormConsumer>
    </FormProvider>
  )
}

// vue2/src/components/FormilyPage/index.vue
<template>
  <FormProvider :key="renderKey" :form="form">
    <slot name="before" />
    <SchemaField :schema="schema" :components="components" :scope="scopeWithAT" />
    <slot name="default" />
    <FormConsumer>
      <template #default="{ form }">
        <router-link v-if="schemaKey" :to="'/designable?key=' + schemaKey">编辑</router-link>
      </template>
    </FormConsumer>
  </FormProvider>
</template>

<script>
import { createForm } from '@formily/core'
import { FormProvider, FormConsumer, createSchemaField } from '@formily/vue'

import * as FormilyElement from '@formily/element'
import * as ProjectComponents from './projectComponents'
import { transformNativeOn } from './transformComponent'
import * as AdminTemplateScope from './adminTemplateScope'

const { SchemaField } = createSchemaField({
  components: {
    ...FormilyElement,
    Input: Object.assign(
      transformNativeOn(FormilyElement.Input),
      {
        TextArea: transformNativeOn(FormilyElement.Input.TextArea)
      }
    ),
    Password: transformNativeOn(FormilyElement.Password),
    Radio: FormilyElement.Radio,
    ...ProjectComponents
  }
})

export {
  SchemaField
}

export default {
  components: {
    FormProvider,
    FormConsumer,
    FormItem: FormilyElement.FormItem,
    SchemaField
  },
  props: {
    schemaKey: {
      type: String,
      default() { return '' }
    },
    schema: {
      type: Object,
      default() { return {} }
    },
    components: {
      type: Object,
      default() { return {} }
    },
    scope: {
      type: Object,
      default() { return {} }
    },
    effects: {
      type: Function,
      default() { return null }
    }
  },
  data() {
    const form = createForm({
      effects: () => {
        this.effects && this.effects()
      }
    })
    return {
      renderKey: 1,
      form
    }
  },
  computed: {
    scopeWithAT() {
      return {
        ...AdminTemplateScope,
        ...this.scope
      }
    }
  },
  watch: {
    schema() {
      this.renderKey++
    }
  }
}
</script>

<style scoped>
</style>
