// react/src/views/Login/index.tsx
import React, { useState } from 'react'

import { Button, Modal } from 'antd'
import { FormilyPage } from '@/components'
import { SocialSign } from './components'
import { Store } from 'formily/views'

import './style.less'

export const Login: React.FunctionComponent = () => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  return (
    <div className="login-container">
      <div className="login-form">
        <div className="title-container">
          <h3 className="title">Login Form</h3>
        </div>
        <FormilyPage schema={Store.Login} schemaKey="Login" />
        <div style={{position: "relative"}}>
          <div className="tips">
            <span>Username : admin</span>
            <span>Password : any</span>
          </div>
          <div className="tips">
            <span style={{marginRight:'18px'}}>Username : editor</span>
            <span>Password : any</span>
          </div>

          <Button className="thirdparty-button" type="primary" onClick={() => setIsModalOpen(true)}>
            Or connect with
          </Button>
        </div>
      </div>
      <Modal title="Or connect with" visible={isModalOpen}
        footer={null}
        onOk={() => setIsModalOpen(false)}
        onCancel={() => setIsModalOpen(false)}>
        Can not be simulated on local, so please combine you own business simulation! ! !
        <br/>
        <br/>
        <br/>
        <SocialSign />
      </Modal>
    </div>
  )
}

// vue2/src/views/login/index.vue
<template>
  <div class="login-container">
    <div class="login-form">
      <div class="title-container">
        <h3 class="title">Login Form</h3>
      </div>
      <FormilyPage :schema="schema" schema-key="Login" />
      <div style="position:relative">
        <div class="tips">
          <span>Username : admin</span>
          <span>Password : any</span>
        </div>
        <div class="tips">
          <span style="margin-right:18px;">Username : editor</span>
          <span>Password : any</span>
        </div>

        <el-button class="thirdparty-button" type="primary" @click="showDialog=true">
          Or connect with
        </el-button>
      </div>
    </div>
    <el-dialog title="Or connect with" :visible.sync="showDialog">
      Can not be simulated on local, so please combine you own business simulation! ! !
      <br>
      <br>
      <br>
      <social-sign />
    </el-dialog>
  </div>
</template>

<script>
import FormilyPage from '@/components/FormilyPage'
import SocialSign from './components/SocialSignin'
import { Store } from 'formily/views'
// import page from 'formily/views/login/index'

export default {
  name: 'Login',
  components: { FormilyPage, SocialSign },
  data() {
    return {
      schema: Store.Login,
      showDialog: false
    }
  },
  watch: {
  },
  created() {
    // window.addEventListener('storage', this.afterQRScan)
  },
  mounted() {
  },
  destroyed() {
    // window.removeEventListener('storage', this.afterQRScan)
  },
  methods: {
  }
}
</script>

<style lang="scss">
/* 修复input 背景不协调 和光标变色 */
/* Detail see https://github.com/PanJiaChen/vue-element-admin/pull/927 */

$bg:#283443;
$light_gray:#fff;
$cursor: #fff;

@supports (-webkit-mask: none) and (not (cater-color: $cursor)) {
  .login-container .el-input input {
    color: $cursor;
  }
}

/* reset element-ui css */
.login-container {

  .formily-element-form-item {
    color: #454545;
    .formily-element-form-item-label {
      display: none;
    }
    .el-input {
      display: inline-block;
      height: 50px;
      border: 1px solid rgba(255, 255, 255, 0.1);
      background: rgba(0, 0, 0, 0.1);
      border-radius: 5px;

      input {
        background: transparent;
        border: 0px;
        -webkit-appearance: none;
        border-radius: 0px;
        color: $light_gray;
        height: 47px;
        caret-color: $cursor;

        &:-webkit-autofill {
          box-shadow: 0 0 0px 1000px $bg inset !important;
          -webkit-text-fill-color: $cursor !important;
        }
      }
    }
  }
}
</style>

<style lang="scss" scoped>
$bg:#2d3a4b;
$dark_gray:#889aa4;
$light_gray:#eee;

.login-container {
  min-height: 100%;
  width: 100%;
  background-color: $bg;
  overflow: hidden;

  .login-form {
    position: relative;
    width: 520px;
    max-width: 100%;
    padding: 160px 35px 0;
    margin: 0 auto;
    overflow: hidden;
  }

  .tips {
    font-size: 14px;
    color: #fff;
    margin-bottom: 10px;

    span {
      &:first-of-type {
        margin-right: 16px;
      }
    }
  }

  .title-container {
    position: relative;

    .title {
      font-size: 26px;
      color: $light_gray;
      margin: 0px auto 40px auto;
      text-align: center;
      font-weight: bold;
    }
  }

  .thirdparty-button {
    position: absolute;
    right: 0;
    bottom: 6px;
  }

  @media only screen and (max-width: 470px) {
    .thirdparty-button {
      display: none;
    }
  }
}
</style>
