// react/src/views/Designable/index.tsx
import React from 'react'
import Provider from '@/designable/main'

import { Store } from 'formily/views'
import { useSearchParams } from 'react-router-dom'


export const Designable: React.FunctionComponent = () => {
  const [params] = useSearchParams()
  const editKey = params.get('key')
  const editData = Store[editKey]
  const returnPath = params.get('returnPath')
  return (
    <Provider
      editKey={editKey}
      returnPath={returnPath}
      editData={editData}
      onSaveData={(data) => {
        console.log(data)
        Store.save(editKey, data)
      }}>
    </Provider>
  )
}

// vue2/src/views/designable/index.vue
<template>
  <div ref='div'></div>
</template>

<script>

import { loadModule } from './systemLoader'
import { Store } from 'formily/views'

export default {
  name: 'Designable',
  data() {
    return {
      _ReactDOM: null
    }
  },
  async mounted() {
    const { React, ReactDOM, Editor } = await loadModule('editor')
    this._ReactDOM = ReactDOM
    const params = this.$route.query
    ReactDOM.render(React.createElement(Editor, {
      editKey: params.key,
      editData: Store[params.key],
      returnPath: params.returnPath,
      onSaveData: (data) => {
        Store.save(params.key || '__draft__', data)
      }
    }), this.$refs.div)
  },
  destroyed() {
    this._ReactDOM.unmountComponentAtNode(this.$refs.div)
  }
}
</script>

<style>

</style>
