// vue2/src/layout/components/Navbar.vue
<template>
  <div class="navbar">
    <hamburger id="hamburger-container" :is-active="sidebar.opened" class="hamburger-container" @toggleClick="toggleSideBar" />

    <breadcrumb id="breadcrumb-container" class="breadcrumb-container" />

    <div class="right-menu">
      <template v-if="device!=='mobile'">
        <div v-if="reactAddress" class="right-menu-item">
          <el-button size="mini" @click="toReact">React</el-button>
        </div>
        <search id="header-search" class="right-menu-item" />

        <error-log class="errLog-container right-menu-item hover-effect" />

        <screenfull id="screenfull" class="right-menu-item hover-effect" />

        <el-tooltip content="Global Size" effect="dark" placement="bottom">
          <size-select id="size-select" class="right-menu-item hover-effect" />
        </el-tooltip>

      </template>

      <el-dropdown class="avatar-container right-menu-item hover-effect" trigger="click">
        <div class="avatar-wrapper">
          <img :src="avatar+'?imageView2/1/w/80/h/80'" class="user-avatar">
          <i class="el-icon-caret-bottom" />
        </div>
        <el-dropdown-menu slot="dropdown">
          <router-link to="/profile/index">
            <el-dropdown-item>Profile</el-dropdown-item>
          </router-link>
          <router-link to="/">
            <el-dropdown-item>Dashboard</el-dropdown-item>
          </router-link>
          <a target="_blank" href="https://github.com/PanJiaChen/vue-element-admin/">
            <el-dropdown-item>Github</el-dropdown-item>
          </a>
          <a target="_blank" href="https://panjiachen.github.io/vue-element-admin-site/#/">
            <el-dropdown-item>Docs</el-dropdown-item>
          </a>
          <el-dropdown-item divided @click.native="logout">
            <span style="display:block;">Log Out</span>
          </el-dropdown-item>
        </el-dropdown-menu>
      </el-dropdown>
    </div>
  </div>
</template>

<script>
import { mapGetters } from 'vuex'
import Breadcrumb from '@/components/Breadcrumb'
import Hamburger from '@/components/Hamburger'
import ErrorLog from '@/components/ErrorLog'
import Screenfull from '@/components/Screenfull'
import SizeSelect from '@/components/SizeSelect'
import Search from '@/components/HeaderSearch'

export default {
  components: {
    Breadcrumb,
    Hamburger,
    ErrorLog,
    Screenfull,
    SizeSelect,
    Search
  },
  data() {
    return {
      reactAddress: process.env.VUE_APP_REACT_EXAMPLE_ADDRESS
    }
  },
  computed: {
    ...mapGetters([
      'sidebar',
      'avatar',
      'device'
    ])
  },
  methods: {
    toReact() {
      location.href = this.reactAddress
    },
    toggleSideBar() {
      this.$store.dispatch('app/toggleSideBar')
    },
    async logout() {
      await this.$store.dispatch('user/logout')
      this.$router.push(`/login?redirect=${this.$route.fullPath}`)
    }
  }
}
</script>

<style lang="scss" scoped>
.navbar {
  height: 50px;
  overflow: hidden;
  position: relative;
  background: #fff;
  box-shadow: 0 1px 4px rgba(0,21,41,.08);

  .hamburger-container {
    line-height: 46px;
    height: 100%;
    float: left;
    cursor: pointer;
    transition: background .3s;
    -webkit-tap-highlight-color:transparent;

    &:hover {
      background: rgba(0, 0, 0, .025)
    }
  }

  .breadcrumb-container {
    float: left;
  }

  .errLog-container {
    display: inline-block;
    vertical-align: top;
  }

  .right-menu {
    float: right;
    height: 100%;
    line-height: 50px;

    &:focus {
      outline: none;
    }

    .right-menu-item {
      display: inline-block;
      padding: 0 8px;
      height: 100%;
      font-size: 18px;
      color: #5a5e66;
      vertical-align: text-bottom;

      &.hover-effect {
        cursor: pointer;
        transition: background .3s;

        &:hover {
          background: rgba(0, 0, 0, .025)
        }
      }
    }

    .avatar-container {
      margin-right: 30px;

      .avatar-wrapper {
        margin-top: 5px;
        position: relative;

        .user-avatar {
          cursor: pointer;
          width: 40px;
          height: 40px;
          border-radius: 10px;
        }

        .el-icon-caret-bottom {
          cursor: pointer;
          position: absolute;
          right: -20px;
          top: 25px;
          font-size: 12px;
        }
      }
    }
  }
}
</style>

// react/src/layout/components/Navbar/index.tsx
import React from 'react'

import {
  Breadcrumb,
  Hamburger,
  ErrorLog,
  Screenfull,
  SizeSelect,
  Search,
} from '@/components'

import {
  Tooltip,
  Dropdown,
  Menu,
  Button,
} from 'antd'

import { useAppState, useUserState } from '@/hooks'
import { NavLink } from 'react-router-dom'

import './style.less'

const vueAddress = process.env.REACT_APP_VUE_EXAMPLE_ADDRESS

export const Navbar: React.FunctionComponent = () => {
  const { appState: {
    sidebar,
    device
  }, appActions: {
    toggleSidebar
  } } = useAppState()

  const { userState, userActions: { logout } } = useUserState()
  return (
    <div className="navbar">
      <Hamburger isActive={sidebar.opened} className="hamburger-container" onClick={() => toggleSidebar()} />
      <Breadcrumb className="breadcrumb-container" />
      <div className="right-menu">
        {device != 'mobile' ? (
          <>
            {vueAddress ? <div className="right-menu-item">
              <Button size="small" onClick={() => {
                location.href = vueAddress
              }}>Vue</Button>
            </div> : null }
            <Search className="right-menu-item" />

            <ErrorLog className="errLog-container right-menu-item hover-effect" />

            <Screenfull className="right-menu-item hover-effect" />

            <Tooltip title="Global Size" placement="bottom">
              <SizeSelect className="right-menu-item hover-effect" />
            </Tooltip>
          </>
        ) : <></>}

        <Dropdown 
          trigger={["click"]}
          overlay={() => {
            return (
              <Menu items={[
                { title: 'Profile', key: 'profile', label: <NavLink to="/profile/index">Profile</NavLink> },
                { title: 'Dashboard', key: 'dashboard', label: <NavLink to="/">Dashboard</NavLink> },
                { title: 'Github', key: 'github', label: <a href='https://github.com/wangwangtou/formily-admin-template'>Github</a> },
                { type: 'divider' },
                { title: 'Log Out', key: 'logout', label: <span style={{display:'block'}} onClick={() => logout()}>Log Out</span> }
              ]}></Menu>
            )
          }}>
          <div className="avatar-container right-menu-item hover-effect">
            <div className="avatar-wrapper">
              <img src={userState.avatar+'?imageView2/1/w/80/h/80'} className="user-avatar"/>
              <i className="el-icon-caret-bottom" />
            </div>
          </div>
        </Dropdown>
      </div>
    </div>
  )
}
