// react/src/components/Sticky/index.tsx
import React, { useEffect, useRef, useState } from 'react'

interface StickyProps {
  stickyTop: number,
  height: number,
  zIndex: number,
  className: string,
}

export const Sticky: React.FunctionComponent<StickyProps> = ({
  stickyTop = 0,
  height,
  zIndex,
  className,
  children
}) => {
  const [state, setState] = useState({
    position: '',
    width: 'auto',
    active: false,
    isSticky: false
  })
  const el = useRef(null)
  useEffect(() => {
    const handleScroll = () => {
      if (!el.current) return
      const width = el.current.getBoundingClientRect().width
      const offsetTop = el.current.getBoundingClientRect().top
      if (offsetTop < stickyTop) {
        if (!state.active) {
          setState({
            position: 'fixed',
            active: true,
            width: width ? width + 'px' : 'auto',
            isSticky: true
          })
        }
        return
      }
      setState({
        position: '',
        width: 'auto',
        active: false,
        isSticky: false
      })
    }
    const handleResize = () => {
      if (!el.current) return
      if (state.isSticky) {
        const width = el.current.getBoundingClientRect().width
        setState({
          ...state,
          width: width ? width + 'px' : 'auto'
        })
      }
    }
    window.addEventListener('scroll', handleScroll)
    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('scroll', handleScroll)
      window.removeEventListener('resize', handleResize)
    }
  }, [])
  return (
    <div style={{height:height+'px',zIndex:zIndex}} ref={el}>
      <div
        className={className}
        style={{top:(state.isSticky ? stickyTop +'px' : ''),zIndex:zIndex, position: state.position,width: state.width,height:height+'px'}}
      >
        {children}
      </div>
    </div>
  )
}

// vue2/src/components/Sticky/index.vue
<template>
  <div :style="{height:height+'px',zIndex:zIndex}">
    <div
      :class="className"
      :style="{top:(isSticky ? stickyTop +'px' : ''),zIndex:zIndex,position:position,width:width,height:height+'px'}"
    >
      <slot>
        <div>sticky</div>
      </slot>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Sticky',
  props: {
    stickyTop: {
      type: Number,
      default: 0
    },
    zIndex: {
      type: Number,
      default: 1
    },
    className: {
      type: [String, Array],
      default: ''
    }
  },
  data() {
    return {
      active: false,
      position: '',
      width: undefined,
      height: undefined,
      isSticky: false
    }
  },
  mounted() {
    this.height = this.$el.getBoundingClientRect().height
    window.addEventListener('scroll', this.handleScroll)
    window.addEventListener('resize', this.handleResize)
  },
  activated() {
    this.handleScroll()
  },
  destroyed() {
    window.removeEventListener('scroll', this.handleScroll)
    window.removeEventListener('resize', this.handleResize)
  },
  methods: {
    sticky() {
      if (this.active) {
        return
      }
      this.position = 'fixed'
      this.active = true
      this.width = this.width + 'px'
      this.isSticky = true
    },
    handleReset() {
      if (!this.active) {
        return
      }
      this.reset()
    },
    reset() {
      this.position = ''
      this.width = 'auto'
      this.active = false
      this.isSticky = false
    },
    handleScroll() {
      const width = this.$el.getBoundingClientRect().width
      this.width = width || 'auto'
      const offsetTop = this.$el.getBoundingClientRect().top
      if (offsetTop < this.stickyTop) {
        this.sticky()
        return
      }
      this.handleReset()
    },
    handleResize() {
      if (this.isSticky) {
        this.width = this.$el.getBoundingClientRect().width + 'px'
      }
    }
  }
}
</script>
